import AppLayout from '@/layouts/AppLayout'
import { NotificationList } from '@/modules/notification-list'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'SMARTEX | Уведомление',
	description: 'Generated by create next app',
}

const NotificationPage = () => (
	<AppLayout>
		<NotificationList />
	</AppLayout>
)

export default NotificationPage
