import AppLayout from '@/layouts/AppLayout'
import { Faq } from '@/modules/faq'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'SMARTEX | Часто задаваемые вопросы',
	description: 'Generated by create next app',
}

const FaqPage = () => (
	<AppLayout>
		<Faq />
	</AppLayout>
)

export default FaqPage
