import AppLayout from '@/layouts/AppLayout'
import { ResetPassword } from '@/modules/reset-password'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'SMARTEX | Сброс пароля',
	description: 'Generated by create next app',
}

const ResetPasswordPage = () => (
	<AppLayout>
		<ResetPassword />
	</AppLayout>
)

export default ResetPasswordPage
