import AppLayout from '@/layouts/AppLayout'
import { AddPurchase } from '@/modules/add-purchase/components/add-purchase/AddPurchase'
import { SearchParcel } from '@/modules/search-parcel'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Добавить покупку',
	description: 'Generated by create next app',
}

const AddPurchasePage = () => (
	<AppLayout>
		<SearchParcel />
		<AddPurchase />
	</AppLayout>
)

export default AddPurchasePage
