import AppLayout from '@/layouts/AppLayout'
import { UserSettingsPanel } from '@/modules/user-settings-panel'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'SMARTEX | Настройки',
	description: 'Generated by create next app',
}

const SettingPage = () => (
	<AppLayout>
		<UserSettingsPanel />
	</AppLayout>
)

export default SettingPage
