import AppLayout from '@/layouts/AppLayout'
import { Confidants } from '@/modules/confidants'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'SMARTEX | Доверенные лица',
	description: 'Generated by create next app',
}

const ConfidantsPage = () => (
	<AppLayout>
		<Confidants />
	</AppLayout>
)

export default ConfidantsPage
