import AppLayout from '@/layouts/AppLayout'
import { CurrentParcels } from '@/modules/current-parcels'
import { ProfileWidgets } from '@/modules/profile-widgets'
import { SearchParcel } from '@/modules/search-parcel'
import { ShipmentDashboard } from '@/modules/shipment-dashboard'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'SMARTEX | Личный кабинет',
	description: 'Generated by create next app',
}

const DashboardPage = () => (
	<AppLayout>
		<SearchParcel />
		<ProfileWidgets />
		<ShipmentDashboard />
		<CurrentParcels />
	</AppLayout>
)

export default DashboardPage
