export const APP_LINKS_KEYS = {
	home: '/',
	faq: '/faq',
	topUp: '/top-up',
	message: '/message',
	setting: '/setting',
	confidants: '/confidants',
	usaParcel: '/my-parcel/usa',
	notification: '/notification',
	personalInfo: '/personal-info',
	homeDelivery: '/home-delivery',
	turkishParcel: '/my-parcel/turkish',
	chinaAutoParcel: '/my-parcel/china-auto',
	chinaAviaParcel: '/my-parcel/china-avia',
	addPurchase: '/my-parcel/add-purchase',
	resetPassword: '/setting/reset-password',
	usaForeignAddress: '/foreign-addresses/usa',
	turkishForeignAddress: '/foreign-addresses/turkish',
	chinaAutoForeignAddress: '/foreign-addresses/china-auto',
	chinaAviaForeignAddress: '/foreign-addresses/china-avia',
} as const

export const pathSegmentNameMap: Record<string, string> = {
	faq: 'FAQ',
	usa: 'США',
	turkish: 'Турция',
	setting: 'Настройки',
	details: 'Подробнее',
	more: 'Больше новостей',
	notification: 'Уведомление',
	confidants: 'Доверенные лица',
	'foreign-addresses': 'Зарубежные адреса',
	'top-up': 'Пополнить',
	'my-parcel': 'Мои посылки',
	'china-auto': 'Китай (авто)',
	'china-avia': 'Китай (авиа)',
	'reset-password': 'Сброс пароля',
	'personal-info': 'Личная информация',
	'home-delivery': 'Доставка до дома',
	'trusted-persons': 'Доверенные лица',
	'add-purchase': 'Добавить покупку',
}
