import AppLayout from '@/layouts/AppLayout'
import { UpdateProfile } from '@/modules/update-profile'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'SMARTEX | Личная информация',
	description: 'Generated by create next app',
}

const PersonalInfoPage = () => (
	<AppLayout>
		<UpdateProfile />
	</AppLayout>
)

export default PersonalInfoPage
