import AppLayout from '@/layouts/AppLayout'
import { ChangeDepositMethod } from '@/modules/change-deposit-method'
import { CurrencyRate } from '@/modules/currency-rate'
import { SearchParcel } from '@/modules/search-parcel'
import { Transactions } from '@/modules/transactions'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'SMARTEX | Пополнить',
	description: 'Generated by create next app',
}

const TopUpPage = () => (
	<AppLayout>
		<SearchParcel />
		<div className='grid grid-cols-2 gap-6 my-6 w750:flex-col w750:grid-cols-1'>
			<ChangeDepositMethod />
			<CurrencyRate />
		</div>
		<Transactions />
	</AppLayout>
)

export default TopUpPage
