import AppLayout from '@/layouts/AppLayout'
import { ParcelsFrom } from '@/modules/parcels-from/components/parcel-from-turkey/ParcelsFrom'
import { SearchParcel } from '@/modules/search-parcel'
import { Country, DeliveryType } from '@proto/proto/service'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Мои посылки | США',
	description: 'Generated by create next app',
}

const UsaPage = () => (
	<AppLayout>
		<SearchParcel />
		<ParcelsFrom country={Country.USA} deliveryType={DeliveryType.AIR} />
	</AppLayout>
)

export default UsaPage
