import AppLayout from '@/layouts/AppLayout'
import { AddNewAddress } from '@/modules/add-new-address'
import { FreeShippingZone } from '@/modules/free-shipping-zone'
import { MyAddresses } from '@/modules/my-addresses'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'SMARTEX | Доставка до дома',
	description: 'Generated by create next app',
}

const HomeDeliveryPage = () => (
	<AppLayout>
		<div className='flex w-full gap-6 w1050:flex-col'>
			<div className='max-w-[528px] w-full flex flex-col gap-6 w1050:max-w-full'>
				<AddNewAddress />
				<MyAddresses />
			</div>
			<FreeShippingZone />
		</div>
	</AppLayout>
)

export default HomeDeliveryPage
